hl.on("hyprland.start", function()
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("waybar")
  hl.exec_cmd(os.getenv("HOME") .. "/.config/waybar/scripts/ws-listen.sh")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("flatpak run com.discordapp.Discord")
  hl.exec_cmd("slimbookbattery --minimize")
  hl.exec_cmd("am -u")
  hl.exec_cmd("swayosd-server")

  hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "oomox-arc-dark"')
  hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
  hl.exec_cmd("systemctl start --user wallpaperset.service")
  hl.exec_cmd("systemctl start --user hypr-keybind-config-switcher.service")
  hl.exec_cmd("wl-paste --watch cliphist store")

  hl.exec_cmd("hyprpm reload -n")
end)
