-- generated by switch-keybinds.sh (laptop-only)
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"),         { locked = true })
hl.bind("switch:on:Lid Switch",  hl.dsp.exec_cmd("hyprctl dispatch dpms on"),  { locked = true })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.333333, vrr = 1 })
