# Turn laptop screen on and off when opening and closing lid
bindl = , switch:on:Lid Switch, exec, bash ~/.config/hypr/UserScripts/select-keybind-rules/disable-builtin.sh
bindl = , switch:off:Lid Switch, exec, bash ~/.config/hypr/UserScripts/select-keybind-rules/enable-builtin.sh
