# Turn laptop screen on and off when opening and closing lid
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 2560x1600, -2560x0, 1"

