#!/bin/bash
# Generate config/overrides.lua with lid-switch binds (and a laptop monitor
# fallback) based on the current monitor count, then reload Hyprland.

tries=0
max_tries=20
while [ "$(hyprctl monitors 2>/dev/null | grep -c '^Monitor')" -lt 1 ]; do
    sleep 0.2
    tries=$((tries + 1))
    if [ "$tries" -ge "$max_tries" ]; then
        echo "Timed out waiting for monitors"
        exit 1
    fi
done

monitor_count=$(hyprctl monitors | grep -c '^Monitor')
target="$HOME/.config/hypr/config/overrides.lua"
mkdir -p "$(dirname "$target")"

if [ "$monitor_count" -eq 1 ]; then
    cat > "$target" <<'LUA'
-- generated by switch-keybinds.sh (laptop-only)
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"),         { locked = true })
hl.bind("switch:on:Lid Switch",  hl.dsp.exec_cmd("hyprctl dispatch dpms on"),  { locked = true })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.333333, vrr = 1 })
LUA
    echo "Loaded single-monitor overrides"
elif [ "$monitor_count" -ge 2 ]; then
    cat > "$target" <<'LUA'
-- generated by switch-keybinds.sh (external displays)
hl.bind("switch:on:Lid Switch",  hl.dsp.exec_cmd("bash ~/.config/hypr/UserScripts/select-keybind-rules/disable-builtin.sh"), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("bash ~/.config/hypr/UserScripts/select-keybind-rules/enable-builtin.sh"),  { locked = true })
LUA
    echo "Loaded multi-monitor overrides"
else
    echo "No active monitors detected!"
    exit 1
fi

hyprctl reload
