#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Nordzy-cursors-white
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Nordzy-hyprcursors-white
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORM,wayland;xcb

