monitor = desc:Microstep MAG321UP OLED, 3840x2160@60Hz, 3840x0,1, vrr,1
monitor = desc:LG Electronics LG HDR 4K 411NTRL54206, 3840x2160@60.00Hz, 0x0,1, vrr,1
monitor = desc:ViewSonic Corporation VX3276-QHD VSX2327A0013, 2560x1440@60Hz, 7680x-260, auto, transform, 3, vrr,1
monitor = eDP-1, preferred,auto,1.333333, vrr, 1
monitor=,preferred,auto,auto

