# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

windowrule = opacity 0.97 override 0.9 override, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = opacity 1.0 override 1.0 override,class:jetbrains-.*
windowrule = float, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer|Omarchy)$
windowrule = center, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer|Omarchy)$
windowrule = size 800 600, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer)$
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)

# Float Steam, fullscreen RetroArch
windowrule = float, class:steam
windowrule = center, class:steam, title:Steam
windowrule = opacity 1 1, class:steam
windowrule = fullscreen, class:steam_app_0
windowrule = opacity 1 1, class:steam_app_0
windowrule = fullscreen, class:com.libretro.RetroArch
windowrule = opacity 1 1, class:com.libretro.RetroArch


# Just dash of opacity
windowrule = opacity 1 override 0.97 override, class:^(Chromium|chromium|google-chrome|google-chrome-unstable|zen)$
windowrule = opacity 1 override 1 override, initialTitle:^(youtube.com_/)$ # Youtube
windowrule = opacity 1 override 1 override, class:^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
windowrule = opacity 1 override 1 override, class:^(com.libretro.RetroArch|steam)$


# Picture-in-picture overlays
windowrule = tag +pip, title:(Picture.{0,1}in.{0,1}[Pp]icture)
windowrule = float, tag:pip
windowrule = pin, tag:pip
windowrule = size 600 338, tag:pip
windowrule = keepaspectratio, tag:pip
windowrule = noborder, tag:pip
windowrule = opacity 1 1, tag:pip
windowrule = move 100%-w-40 4%, tag:pip

# Float and center file pickers
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:org.kde.*, title:^(Open.*Files?|Save.*Files?|All Files|Save|Open.*Ark?|Extract.*Ark?)


# Random rules
windowrule = opacity 1 override 1 override, initialClass:^(sykes.gtk.example)$
windowrule = opacity 1 override 1 override, initialClass:^(Microsoft.*)$

