# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

windowrule = opacity 0.97 override 0.9 override, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = opacity 1.0 override 1.0 override,class:jetbrains-.*
windowrule = float, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer|Omarchy)$
windowrule = center, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer|Omarchy)$
windowrule = size 800 600, class:^(org.pulseaudio.pavucontrol|blueman-manager|Impala|org.gnome.NautilusPreviewer)$
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)

# Float Steam, fullscreen RetroArch
windowrule = float, class:^(steam)$
windowrule = fullscreen, class:^(com.libretro.RetroArch)$

# Just dash of opacity
windowrule = opacity 1 override 0.97 override, class:^(Chromium|chromium|google-chrome|google-chrome-unstable|zen)$
windowrule = opacity 1 override 1 override, initialTitle:^(youtube.com_/)$ # Youtube
windowrule = opacity 1 override 1 override, class:^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
windowrule = opacity 1 override 1 override, class:^(com.libretro.RetroArch|steam)$

# Fix some dragging issues with XWayland


