[colors]
; Mapped from your Waybar CSS (background, module bg, foreground, hovers)
; bg: #222630, module bg: #191d24, fg: #88c0d0, hover: #434c5e
bg       = #222630
bg_alt   = #191d24
fg       = #88c0d0
muted    = #6c7086
activebg = #13131d
hover    = #434c5e

; accents used for states (Catppuccin-ish like your i3 colors)
ok       = #a6e3a1
warn     = #f9e2af
urgent   = #f38ba8

