; Polybar main config
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/main]
monitor = ${env:MONITOR:}
width = 100%
height = 30
radius = 14.0
padding = 2
module-margin = 2
separator =
background = ${colors.bg}
foreground = ${colors.fg}
border-size = 0
line-size = 2

; Nerd/FA fonts like in your Waybar CSS
font-0 = "SpaceMono Nerd Font:style=Regular:pixelsize=14;2"
font-1 = "Font Awesome 6 Free:style=Solid:pixelsize=13;2"
font-2 = "Font Awesome 6 Brands:style=Regular:pixelsize=13;2"

enable-ipc = true  ; needed for hook toggles / future IPC tricks

modules-left   = xworkspaces xwindow
modules-center =
modules-right  = notification pulseaudio backlight network bluetooth cpu memory temperature xkeyboard powerprofile battery date tray

