-- Hyprland Lua config entry point. Each concern lives in its own file under config/.
-- See https://wiki.hypr.land/Configuring/Start/

local cfg_dir = os.getenv("HOME") .. "/.config/hypr"
package.path = cfg_dir .. "/?.lua;" .. cfg_dir .. "/?/init.lua;" .. package.path

require("config.programs")       -- shared constants (must load before keybindings)
require("config.monitors")
require("config.environment")
require("config.autostart")
require("config.permissions")
require("config.look-and-feel")
require("config.input")
require("config.keybindings")
require("config.windowrules")

-- config/overrides.lua is generated by UserScripts/select-keybind-rules/switch-keybinds.sh
-- based on monitor count. pcall so a missing file (pre-first-run) is silent.
pcall(require, "config.overrides")
