#!/bin/bash

# Determine the distribution
DISTRO=$(lsb_release -is 2>/dev/null)

if [[ "$DISTRO" == "Ubuntu" || "$DISTRO" == "Neon" ]]; then
    srcFolder=ubuntu

elif [[ "$DISTRO" == "Debian" ]]; then
    srcFolder=debian

elif [ -f "/etyyc/arch-release" ]; then
    srcFolder=arch

elif [ -f "/etc/fedora-release" ]; then
    srcFolder=fedora

elif grep -qi "opensuse" /etc/os-release; then
    srcFolder=opensuse

else
    echo "No supported Distro for install found"
    exit 1
fi

rm -rf ~/.config/nvim 
cp -a ~/.DotFiles/ ~/.DotFiles/$srcFolder/.config/nvim
nvim +PlugInstall
